### ISSUE TITLE
not informative error message thrown in case of invalid input format in body of Content Type - application/xml

### ISSUE THREAD

**Issue by stas-fomenko** [elasticio/rest-api-component#82]
STR:
1. Create flow: step1 -rest-api
2. check enable debug logging check-box
3. Go to: https://www.mocky.io/
 Set:
 - `Status Code`: 200
 -  `Content Type`: - application/xml
 - `body`: {"foo1":"bar1"}
4. Generate request link
5. Retrieve sample using generated link

AR:
Error:
![image](https://user-images.githubusercontent.com/36419533/64245054-74efb580-cf0a-11e9-9c55-5e401880f0f0.png)

Logs:
```
Starting your Docker container ...
Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: {
    at error (/home/apprunner/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/home/apprunner/node_modules/sax/lib/sax.js:677:7)
    at beginWhiteSpace (/home/apprunner/node_modules/sax/lib/sax.js:951:7)
    at SAXParser.write (/home/apprunner/node_modules/sax/lib/sax.js:1006:11)
    at Parser.exports.Parser.Parser.parseString (/home/apprunner/node_modules/xml2js/lib/parser.js:322:31)
    at Parser.parseString (/home/apprunner/node_modules/xml2js/lib/parser.js:5:59)
    at Object.exports.parseString (/home/apprunner/node_modules/xml2js/lib/parser.js:354:19)
    at /home/apprunner/node_modules/xml2js-es6-promise/xml2js-es6-promise.js:5:16
    at new Promise (<anonymous>)
    at module.exports (/home/apprunner/node_modules/xml2js-es6-promise/xml2js-es6-promise.js:4:12)
    at processResponse (/home/apprunner/lib/utils.js:427:16)
[INFO  tini (1)] Spawned child process '/run.sh' with pid '8'
Starting application in apprunner...
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
Will try to start app at /home/apprunner
invokeModuleFunction – init is not found
2019-09-04T09:37:41.613Z utils Input configuration: '{"_account":"5a956edb6d697f0019ef281f","enableDebugLogging":true,"reader":{"auth":{"basic":{"password":"","username":""}},"body":{"contentType":"multipart/form-data","urlencoded":[],"formData":[],"raw":""},"headers":[],"url":"\\"http://www.mocky.io/v2/5d6f85be310000720066066f\\"","method":"GET"},"auth":{"type":"No Auth","basic":{"username":"","password":""},"digest":{"username":"","realm":"","password":"","nonce":"","algorithm":"","qop":"","nonceCount":"","clientNonce":"","opaque":""},"apiKey":{"headerName":"","headerValue":""}}}'
2019-09-04T09:37:41.612Z utils Input message: '{"passthrough":{},"headers":{}}'
2019-09-04T09:37:41.614Z utils Request body: undefined
2019-09-04T09:37:41.614Z utils Request options: '{"method":"get","uri":"http://www.mocky.io/v2/5d6f85be310000720066066f","followRedirect":true,"followAllRedirects":true,"gzip":true,"resolveWithFullResponse":true,"simple":false,"encoding":null}'
2019-09-04T09:37:41.723Z utils Response statusCode 200
2019-09-04T09:37:41.723Z utils Content type: 'application/xml; charset=UTF-8'
2019-09-04T09:37:41.723Z utils HTTP Response headers: {"server":"Cowboy","connection":"close","form-data":"12321","date":"Wed, 04 Sep 2019 09:37:41 GMT","content-type":"application/xml; charset=UTF-8","content-length":"15","via":"1.1 vegur"}
2019-09-04T09:37:41.723Z utils trying to parse as XML
2019-09-04T09:37:41.723Z utils HTTP Response body: '{"foo1":"bar1"}'
2019-09-04T09:37:41.728Z utils Component error: Error: Non-whitespace before first tag. Line: 0 Column: 1 Char: { at error (/home/apprunner/node_modules/sax/lib/sax.js:651:10) at strictFail (/home/apprunner/node_modules/sax/lib/sax.js:677:7) at beginWhiteSpace (/home/apprunner/node_modules/sax/lib/sax.js:951:7) at SAXParser.write (/home/apprunner/node_modules/sax/lib/sax.js:1006:11) at Parser.exports.Parser.Parser.parseString (/home/apprunner/node_modules/xml2js/lib/parser.js:322:31) at Parser.parseString (/home/apprunner/node_modules/xml2js/lib/parser.js:5:59) at Object.exports.parseString (/home/apprunner/node_modules/xml2js/lib/parser.js:354:19) at /home/apprunner/node_modules/xml2js-es6-promise/xml2js-es6-promise.js:5:16 at new Promise (<anonymous>) at module.exports (/home/apprunner/node_modules/xml2js-es6-promise/xml2js-es6-promise.js:4:12) at processResponse (/home/apprunner/lib/utils.js:427:16)
at SAXParser.write (/home/apprunner/node_modules/sax/lib/sax.js:1006:11)
at module.exports (/home/apprunner/node_modules/xml2js-es6-promise/xml2js-es6-promise.js:4:12)
Column: 1
at beginWhiteSpace (/home/apprunner/node_modules/sax/lib/sax.js:951:7)
at Parser.parseString (/home/apprunner/node_modules/xml2js/lib/parser.js:5:59)
at /home/apprunner/node_modules/xml2js-es6-promise/xml2js-es6-promise.js:5:16
Error: Non-whitespace before first tag.
at error (/home/apprunner/node_modules/sax/lib/sax.js:651:10)
at Parser.exports.Parser.Parser.parseString (/home/apprunner/node_modules/xml2js/lib/parser.js:322:31)
at processResponse (/home/apprunner/lib/utils.js:427:16)
Line: 0
Char: {
at strictFail (/home/apprunner/node_modules/sax/lib/sax.js:677:7)
at Object.exports.parseString (/home/apprunner/node_modules/xml2js/lib/parser.js:354:19)
at new Promise (<anonymous>)
```

ER:
Error message about invalid input format in request body is shown

**Comment by andrewreshitko** [comment]
The component is deprecated.
The task is not relevant anymore.
