### ISSUE TITLE
Override default handling of Content-Type option `Store as attachment` does not create an attachment

### ISSUE THREAD

**Issue by stas-fomenko** [elasticio/rest-api-component#92]
Description:
Override default handling of Content-Type option `Store as attachment` does not create an attachment, it throws an error message instead of it in a case when sample was not retrieved on previous step, but was added manually

Precondition: 
1. Use component hash: `0ec42d0c44eac0fc16bb75d26f94b4d9f982f338` (`add-contentType-override` branch)

STR:
1. Check if mock url is valid if no create a new one: http://www.mocky.io/v2/5de8aa263100000f006b12f8
2. Use trigger or action 
2.1 if action used - create flow: simple trigger (add sample manually - do not retrieve sample) 
3. Input:
Method: GET 
URL: "http://www.mocky.io/v2/5de8aa263100000f006b12f8" 
Override Content-Type: Store as attachment
All other input parameters: Default
4. Retrieve sample

AR: `Error! Cannot set property '899821b0-172c-11ea-bab0-a5323de0b762_1575529064267' of undefined`

debug task logs (trace):
```
Starting your Docker container ...
TypeError: Cannot set property '862c8ab0-1750-11ea-9047-0949ca0be914_1575544520411' of undefined
    at Object.addAttachment (/home/apprunner/lib/attachments.js:6:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[INFO  tini (1)] Spawned child process '/run.sh' with pid '8'
Starting application in apprunner...
Will try to start app at /home/apprunner
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
Connected to AMQP
Opened subscribe channel
Opened publish channel
Received step data: {"id":"step_1","comp_id":"5a968a9cd0b9710007c6002d","function":"httpRequestTrigger","config":{"_account":"5de8cf7e87ad29c8fe150287","overrideContentType":"storeAsAttachment","reader":{"auth":{"basic":{"password":"","username":""}},"body":{"contentType":"multipart/form-data","urlencoded":[],"formData":[],"raw":""},"headers":[],"url":"\"http://www.mocky.io/v2/5de8aa263100000f006b12f8\"","method":"GET"},"auth":{"type":"No Auth","basic":{"username":"","password":""},"apiKey":{"headerName":"","headerValue":""},"hmacSecret":null}},"is_passthrough":true,"variables":{}}
Component path is: /home/apprunner
Root files: [".circleci",".eslintrc.js",".gitignore",".heroku",".npmrc",".profile.d",".release","CHANGELOG.md","README.md","circle.yml","component.json","lib","logo.png","node_modules","package-lock.json","package.json","sail.sh","serve.sh","test","verifyCredentials.js"]
Actions: ["httpRequestAction"]
Triggers: ["httpRequestTrigger"]
Successfully loaded /home/apprunner/component.json
About to initialize component for execution
Trying to find module at: /home/apprunner/lib/triggers/httpRequestTrigger.js
Component execution initialized successfully
invokeModuleFunction – init is not found
Start listening for messages on 5a82f375a847400007c8d569:5de8e6c4dfaee84f463585c0/debug:step_1:messages
Message received: {"fields":{"consumerTag":"amq.ctag-YVOA6DujQ7qLJZqcC5c78Q","deliveryTag":1,"redelivered":false,"exchange":"","routingKey":"5a82f375a847400007c8d569:5de8e6c4dfaee84f463585c0/debug:step_1:messages"},"properties":{"contentType":"application/json","contentEncoding":"utf8","headers":{"taskId":"5de8e6c4dfaee84f463585c0","execId":"493e8eb5761e42ee9f660ed6fde12ca5","userId":"5a82f375a847400007c8d56a","workspaceId":"5a82f375a847400007c8d569","type":"debug","status":"active","threadId":"fb082366-fd56-4691-9b07-73a71e998d4b","x-eio-meta-trace-id":"fb082366-fd56-4691-9b07-73a71e998d4b","messageId":"c116af3d-5eae-4ca9-ab60-2b6187c4ac75"}},"content":{"type":"Buffer","data":[83,83,122,83,90,115,74,121,55,85,109,118,120,120,88,103,72,77,102,77,69,49,80,111,51,105,111,89,111,117,101,86,67,122,103,65,67,98,110,86,101,69,48,61]}}
processMessage received
Trigger or action: httpRequestTrigger
Trying to find module at: /home/apprunner/lib/triggers/httpRequestTrigger.js
processMessage emit error
Cannot set property '862c8ab0-1750-11ea-9047-0949ca0be914_1575544520411' of undefined
processMessage emit end
Message #1 reject
Pushing to exchange=5a82f375a847400007c8d569_org, routingKey=5a82f375a847400007c8d569.5de8e6c4dfaee84f463585c0/debug.step_1.error_debug, data="{\"error\":\"KK9K/ozpYMg6cszSd78z4QuFHwCrzcYfk0rBxQDnlA1HsgDBtmaeEsOzSiBT7AiKm27yF4yqw8lHO8gD+ziSELLg4pKfFMBIVu0E2zWeNhJCe++3ydztlzIkVzn0NMKbRdv/780WfdR9Pi3sKDnR+F65itKQdf4qL72LHaeU53G7DbrpNYBX70RQ+dDU8vErf87ey541Q8APmd1AGNtDrX3Wu45V4Zwdd53IuXYkOuHJrM0pXHq0+2VEdju+T/vurrWPFmHg0f03fyXNlLyt+8vr1oQ+JYXweoxBM8RPDVbeC6YdLG/k11ZNq3WnvhtxI9g9Tw145tL/dxp8Si+jXWaHHtVNWdo5zDSqIJuHlZR0cZHjUlyHmJ/Rfb8mtjREJDdsGUVOqr37JPBojYmdDVmMVpWWdeONj5qLJr+7fd7X7yW9Q5uP8rYGBsmJghRa34aUcfL4M4ulg/m6mzDByS7kkee5tE8n/oGgGWo2dneS8varqNqkUU+IgaZRIMoe\",\"errorInput\":\"SSzSZsJy7UmvxxXgHMfME1Po3ioYoueVCzgACbnVeE0=\"}", options={"contentType":"application/json","contentEncoding":"utf8","mandatory":true,"headers":{"taskId":"5de8e6c4dfaee84f463585c0","execId":"493e8eb5761e42ee9f660ed6fde12ca5","workspaceId":"5a82f375a847400007c8d569","userId":"5a82f375a847400007c8d56a","x-eio-meta-trace-id":"fb082366-fd56-4691-9b07-73a71e998d4b","threadId":"fb082366-fd56-4691-9b07-73a71e998d4b","parentMessageId":"c116af3d-5eae-4ca9-ab60-2b6187c4ac75","containerId":"58475b06-3350-43d2-8822-62da16c486f1","stepId":"step_1","compId":"5a968a9cd0b9710007c6002d","function":"httpRequestTrigger","start":1575544520335,"cid":1,"end":1575544520570,"messageId":"9003d19f-a96c-4a40-90ae-8f03aa199335"}}
Current memory usage: 22.979156494140625 Mb
```
ER: Attchment is created

**Comment by andrewreshitko** [comment]
The component is deprecated.
The task is not relevant anymore.
